alias bi = brew install
alias bu = brew uninstall
alias buc = brew uninstall --cask
alias e = emacsclient
alias gc = git checkout
alias gl = git log
alias gst = git status
alias l = ls
alias la = ls -la
alias ldot = ls .*
alias ll = ls -l
alias m = make
alias md = mkdir
alias n = npm
alias ni = npm -i
alias open = ^open
alias ors = darwin-rebuild switch --flake ~/projects/personal/dotfiles/nix/
alias q = exit
alias s = z
alias y = yarn
alias ya = yarn add
