#!/usr/bin/env sh

if [ $(uname -s) = 'Linux' ]; then
    alias ors='sudo nixos-rebuild switch'
elif [ $(uname -s) = 'Darwin' ]; then
    alias ors='darwin-rebuild switch'
fi

# emacs-vterm
if [ -n "$INSIDE_EMACS" ]; then
    alias vi='emacsclient -n'
    alias vim='emacsclient -n'
    alias emacs='emacsclient -n'
fi

alias mu='mr -j 9 update'
alias mn='commit_and_push notes'
alias mp='commit_and_push pages'

function commit_and_push() {
    cd ~/projects/personal/$1 \
        && git add --all \
        && git commit -m "$(date +'manual: [%F %a %T]')" \
        && git push
    cd -
}
