# Managed by GNU Stow from this dotfiles repository.

include ./themes/AtomOneLight.conf

# Shell integration is sourced and configured manually.
shell_integration no-rc

allow_remote_control no
confirm_os_window_close 0
copy_on_select clipboard
editor emacsclient
exe_search_path +/etc/profiles/per-user/kevin/bin
font_family FiraCode Nerd Font Mono
hide_window_decorations no
shell /bin/zsh -l

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map cmd+, launch --type=background /bin/zsh -lc 'exec emacsclient -n ~/.config/kitty/kitty.conf'
map cmd+< load_config_file
