# Managed by GNU Stow from this dotfiles repository.

include ./themes/AtomOneLight.conf

allow_remote_control no
confirm_os_window_close 0
copy_on_select clipboard
editor emacsclient
exe_search_path /opt/homebrew/bin
exe_search_path ~/.local/bin
exe_search_path +/etc/profiles/per-user/kevin/bin
font_family JetBrainsMono Nerd Font
font_size 13
symbol_map U+3000-U+303F,U+3400-U+4DBF,U+4E00-U+9FFF,U+F900-U+FAFF,U+FF00-U+FFEF Weibei SC
tab_bar_edge top
tab_title_template "{custom}"
watcher title_watcher.py
hide_window_decorations titlebar-only
window_margin_width 6
placement_strategy center
shell /etc/profiles/per-user/kevin/bin/nu -l
startup_session state/startup.kitty-session
action_alias save_startup_session save_as_session --save-only --use-foreground-process --match state:focused_os_window ~/.config/kitty/state/startup.kitty-session

map cmd+t new_tab_with_cwd
map ctrl+shift+t new_tab_with_cwd
map ctrl+q>s combine : save_startup_session : launch --type=background /bin/zsh -lc 'exec ~/.config/kitty/kitty-session-postprocess ~/.config/kitty/state/startup.kitty-session'
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9
map cmd+, launch --type=background /bin/zsh -lc 'exec emacsclient -n ~/.config/kitty/kitty.conf'
map cmd+< load_config_file
