;;; init.el --- Xandeer's Emacs Configuration file.            -*- lexical-binding: t; -*-
;; Copyright (C) 2020  Xandeer

;;; Commentary:

;; Xandeer's emacs.d init file.

;;----------------------------------------------------------------------------
;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file located at
;; index.org
;;
;; You should make any changes there and regenerate it from Emacs org-mode
;; using C-c C-v t
;;----------------------------------------------------------------------------

;;; Code:

(setq-default lexical-binding t)

;;------------------------------------------------------------------------------
;; Bootstrap
(add-to-list 'load-path (expand-file-name "config" user-emacs-directory))
(require 'xandeer-bootstrap)

(xandeer/local-repo core)
(require 'xandeer-core)

(xandeer/local-repo editor)
(require 'xandeer-editor)

(xandeer/local-repo tools)
(require 'xandeer-tools)

(xandeer/local-repo langs)
(require 'xandeer-langs)

(xandeer/local-repo org)
(require 'xandeer-org)

(xandeer/local-repo ui)
(require 'xandeer-ui)

;;----------------------------------------------------------------------------
;; Epilogue
;;----------------------------------------------------------------------------

(run-hooks 'xandeer/config-before-hook)

(setq custom-file (no-littering-expand-etc-file-name "custom.el"))

(add-hook 'after-init-hook #'(lambda () (run-hooks 'xandeer/config-after-hook)))

(when (file-exists-p custom-file)
  (load custom-file))

(when *server*
  (server-start))
;;; init.el ends here
