;;; x-meow.el --- x-meow -*- lexical-binding: t -*-
;;; Commentary:
;;; Code:

(defun x--meow-setqs ()
  (setq meow-cursor-type-insert '(bar . 3))
  (setq meow-motion-remap-prefix "s-")
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty))

(defun x--meow-define-motion-keys ()
  (meow-motion-overwrite-define-key
   '("j" . meow-next)
   '("k" . meow-prev)))

(defun x--meow-define-leader-keys ()
  (meow-leader-define-key
   ;; SPC j/k will run the original command in MOTION state.
   '("j" . meow-motion-origin-command)
   '("k" . meow-motion-origin-command)
   ;; high frequency keybindings
   '("e" . "C-x C-e")
   '(")" . "C-)")
   '("}" . "C-}")
   '("." . "M-.")
   '("," . "M-,")
   ;; window management
   '("w" . other-window)
   '("W" . delete-window)
   '("o" . delete-other-windows)
   ;; high frequency commands
   '(";" . comment-dwim)
   '("p" . project-find-file)
   '("d" . dired)
   '("b" . switch-to-buffer)
   '("f" . org-roam-node-find)
   '("i" . imenu)
   '("a" . magit)
   ;; toggles
   '("L" . display-line-numbers-mode)
   '("t" . telega)
   ;; '("r" . org-roam-mode)
   ;; Use SPC (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet)))

(defun x--meow-define-normal-keys ()
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-append-at-end)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("C" . meow-change-save)
   '("d" . meow-kill)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("F" . meow-find-expand)
   '("g" . x/ace-pinyin-goto-char-2)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-insert-at-begin)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("N" . meow-pop-search)
   '("o" . meow-open-below)
   '("O" . meow-open-above)
   '("p" . meow-yank)
   '("P" . meow-yank-pop)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-reverse)
   '("R" . meow-swap-grab)
   '("s" . er/expand-region)
   '("t" . meow-till)
   '("T" . meow-till-expand)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("V" . meow-kmacro-matches)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-kmacro-lines)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("Z" . meow-pop-all-selection)
   '("&" . meow-query-replace)
   '("%" . meow-query-replace-regexp)
   '("'" . repeat)
   '("\\" . quoted-insert)
   '("\/" . meow-visit)
   '("<escape>" . meow-cancel)))

(defun x--meow-enable-local-insert ()
  "Set insert as default mode."
  (setq-default meow-normal-mode nil)
  (setq-default meow-insert-mode t))

(advice-add 'meow--global-enable :after 'x--meow-enable-local-insert)

(defun x--meow-setup ()
  "Meow setup."
  (x--meow-setqs)
  (x--meow-define-motion-keys)
  (x--meow-define-leader-keys)
  (x--meow-define-normal-keys))

(require-package 'meow)
(x/append-init-hook 'meow-global-mode)
(with-eval-after-load 'meow-core
  (require 'meow-cheatsheet)
  (require 'meow-helpers)
  (x--meow-setup))

(provide 'x-meow)
;;; x-meow.el ends here
