#!/usr/bin/env sh

# go path
export GOPATH="${HOME}/.go"

# update path
export PATH=/usr/local/bin:${PATH}:/sbin

# add go path
export PATH="/usr/local/go/bin:${GOPATH}/bin:${PATH}"

# add rust path
export PATH="${HOME}/.cargo/bin:${PATH}"

# update cdpath
export CDPATH=${CDPATH}:${GOPATH}/src/github.com:${GOPATH}/src/golang.org:${GOPATH}/src

# update path for gnu coreutils, make & find on darwin
export PATH=/usr/local/opt/coreutils/libexec/gnubin:${PATH}
export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:${MANPATH}
export PATH=/usr/local/opt/make/libexec/gnubin:${PATH}
export MANPATH=/usr/local/opt/make/libexec/gnuman:${MANPATH}
export PATH=/usr/local/opt/findutils/libexec/gnubin:${PATH}
export MANPATH=/usr/local/opt/findutils/libexec/gnuman:${MANPATH}


# add android path
export SDK_DIR=~/Library/Android/sdk
export PATH=$PATH:$SDK_DIR/platform-tools
export PATH=$PATH:$SDK_DIR/tools

# add doom path
export PATH=$PATH:$HOME/.emacs.d/bin
