#!/usr/bin/env sh

if [[ "$XANDEER_PROFILE" != loaded ]] ; then
    export XANDEER_PROFILE=loaded

    # update path for gnu coreutils, make & find on darwin
    export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
    export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH
    export PATH=/usr/local/opt/make/libexec/gnubin:$PATH
    export MANPATH=/usr/local/opt/make/libexec/gnuman:$MANPATH
    export PATH=/usr/local/opt/findutils/libexec/gnubin:$PATH
    export MANPATH=/usr/local/opt/findutils/libexec/gnuman:$MANPATH

    # add android path
    if [[ "$OSTYPE" = darwin* ]]; then
        export SDK_DIR=~/Library/Android/sdk
        export PATH=$SDK_DIR/platform-tools:$PATH
        export PATH=$SDK_DIR/tools:$PATH
    fi

    # add rust path
    export PATH=$HOME/.cargo/bin:$PATH

    # add doom path
    export PATH=$HOME/.emacs.d/bin:$PATH
fi
